// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/chat.dart';
import 'api/fs.dart';
import 'api/models.dart';
import 'api/parser.dart';
import 'api/rag.dart';
import 'api/search.dart';
import 'api/settings.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1936808522;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_munnin',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiSettingsAddRecentWiki({required String wikiPath});

  Future<AppSettings> crateApiSettingsAppSettingsDefault();

  DbHealthStatus crateApiSearchCheckDbHealth({required String wikiRoot});

  Future<bool> crateApiRagClearIndex({required String wikiRoot});

  Future<void> crateApiFsCreateDirectory({required String path});

  Future<void> crateApiFsCreateFile({required String path});

  Future<CrowMetadata> crateApiModelsCrowMetadataDefault();

  Future<void> crateApiFsDeleteItem({required String path});

  Future<String> crateApiParserDeltaToMarkdown({
    required List<TextChunk> chunks,
  });

  List<ChatMessage> crateApiChatGetChatMessages({
    required String wikiRoot,
    required String sessionId,
  });

  List<ChatSession> crateApiChatGetChatSessions({required String wikiRoot});

  String crateApiSimpleGreet({required String name});

  bool crateApiSearchIndexDocument({
    required String filePath,
    required String rawMarkdown,
  });

  Future<bool> crateApiRagIndexFile({
    required String wikiRoot,
    required String filePath,
    required String content,
  });

  Future<void> crateApiSimpleInitApp();

  bool crateApiChatInitChatDb({required String wikiRoot});

  Future<bool> crateApiRagInitEmbedder();

  bool crateApiSearchInitSearchDb({required String wikiRoot});

  Future<void> crateApiFsInitWiki({
    required String rootPath,
    required String title,
  });

  AppSettings crateApiSettingsLoadSettings();

  Future<List<TextChunk>> crateApiParserMarkdownToDelta({
    required String markdown,
  });

  Future<CrowFile> crateApiFsReadAnchor({required String rootPath});

  Future<String> crateApiFsReadFileAsString({required String path});

  Future<Page> crateApiFsReadPage({
    required String rootPath,
    required String relPath,
  });

  Future<bool> crateApiSearchRebuildIndex({required String wikiRoot});

  Future<void> crateApiFsRenameItem({
    required String oldPath,
    required String newPath,
  });

  bool crateApiChatSaveChatMessage({
    required String wikiRoot,
    required ChatMessage message,
  });

  bool crateApiChatSaveChatSession({
    required String wikiRoot,
    required ChatSession session,
  });

  void crateApiSettingsSaveGoogleApiKey({required String key});

  void crateApiSettingsSaveTheme({required int index});

  Future<TreeNode> crateApiFsScanDirectory({required String rootPath});

  List<SearchResult> crateApiSearchSearchDocuments({
    required String query,
    required int mode,
  });

  Future<List<ChunkResult>> crateApiRagSearchSimilar({
    required String wikiRoot,
    required String query,
    required BigInt limit,
  });

  Future<TextAttributes> crateApiModelsTextAttributesDefault();

  Future<void> crateApiFsWriteAnchor({
    required String rootPath,
    required CrowFile crowFile,
  });

  Future<void> crateApiFsWriteFileAsString({
    required String path,
    required String content,
  });

  Future<void> crateApiFsWritePage({
    required String rootPath,
    required String relPath,
    required Page page,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiSettingsAddRecentWiki({required String wikiPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(wikiPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsAddRecentWikiConstMeta,
        argValues: [wikiPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsAddRecentWikiConstMeta =>
      const TaskConstMeta(debugName: "add_recent_wiki", argNames: ["wikiPath"]);

  @override
  Future<AppSettings> crateApiSettingsAppSettingsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_settings,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsAppSettingsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsAppSettingsDefaultConstMeta =>
      const TaskConstMeta(debugName: "app_settings_default", argNames: []);

  @override
  DbHealthStatus crateApiSearchCheckDbHealth({required String wikiRoot}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(wikiRoot, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_db_health_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSearchCheckDbHealthConstMeta,
        argValues: [wikiRoot],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchCheckDbHealthConstMeta =>
      const TaskConstMeta(debugName: "check_db_health", argNames: ["wikiRoot"]);

  @override
  Future<bool> crateApiRagClearIndex({required String wikiRoot}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(wikiRoot, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRagClearIndexConstMeta,
        argValues: [wikiRoot],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRagClearIndexConstMeta =>
      const TaskConstMeta(debugName: "clear_index", argNames: ["wikiRoot"]);

  @override
  Future<void> crateApiFsCreateDirectory({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFsCreateDirectoryConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFsCreateDirectoryConstMeta =>
      const TaskConstMeta(debugName: "create_directory", argNames: ["path"]);

  @override
  Future<void> crateApiFsCreateFile({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFsCreateFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFsCreateFileConstMeta =>
      const TaskConstMeta(debugName: "create_file", argNames: ["path"]);

  @override
  Future<CrowMetadata> crateApiModelsCrowMetadataDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_crow_metadata,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsCrowMetadataDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsCrowMetadataDefaultConstMeta =>
      const TaskConstMeta(debugName: "crow_metadata_default", argNames: []);

  @override
  Future<void> crateApiFsDeleteItem({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFsDeleteItemConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFsDeleteItemConstMeta =>
      const TaskConstMeta(debugName: "delete_item", argNames: ["path"]);

  @override
  Future<String> crateApiParserDeltaToMarkdown({
    required List<TextChunk> chunks,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_text_chunk(chunks, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiParserDeltaToMarkdownConstMeta,
        argValues: [chunks],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParserDeltaToMarkdownConstMeta =>
      const TaskConstMeta(debugName: "delta_to_markdown", argNames: ["chunks"]);

  @override
  List<ChatMessage> crateApiChatGetChatMessages({
    required String wikiRoot,
    required String sessionId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(wikiRoot, serializer);
          sse_encode_String(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chat_message,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatGetChatMessagesConstMeta,
        argValues: [wikiRoot, sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatGetChatMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "get_chat_messages",
        argNames: ["wikiRoot", "sessionId"],
      );

  @override
  List<ChatSession> crateApiChatGetChatSessions({required String wikiRoot}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(wikiRoot, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chat_session,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatGetChatSessionsConstMeta,
        argValues: [wikiRoot],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatGetChatSessionsConstMeta =>
      const TaskConstMeta(
        debugName: "get_chat_sessions",
        argNames: ["wikiRoot"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  bool crateApiSearchIndexDocument({
    required String filePath,
    required String rawMarkdown,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          sse_encode_String(rawMarkdown, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSearchIndexDocumentConstMeta,
        argValues: [filePath, rawMarkdown],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchIndexDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "index_document",
        argNames: ["filePath", "rawMarkdown"],
      );

  @override
  Future<bool> crateApiRagIndexFile({
    required String wikiRoot,
    required String filePath,
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(wikiRoot, serializer);
          sse_encode_String(filePath, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRagIndexFileConstMeta,
        argValues: [wikiRoot, filePath, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRagIndexFileConstMeta => const TaskConstMeta(
    debugName: "index_file",
    argNames: ["wikiRoot", "filePath", "content"],
  );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiChatInitChatDb({required String wikiRoot}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(wikiRoot, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatInitChatDbConstMeta,
        argValues: [wikiRoot],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatInitChatDbConstMeta =>
      const TaskConstMeta(debugName: "init_chat_db", argNames: ["wikiRoot"]);

  @override
  Future<bool> crateApiRagInitEmbedder() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRagInitEmbedderConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRagInitEmbedderConstMeta =>
      const TaskConstMeta(debugName: "init_embedder", argNames: []);

  @override
  bool crateApiSearchInitSearchDb({required String wikiRoot}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(wikiRoot, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSearchInitSearchDbConstMeta,
        argValues: [wikiRoot],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchInitSearchDbConstMeta =>
      const TaskConstMeta(debugName: "init_search_db", argNames: ["wikiRoot"]);

  @override
  Future<void> crateApiFsInitWiki({
    required String rootPath,
    required String title,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rootPath, serializer);
          sse_encode_String(title, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFsInitWikiConstMeta,
        argValues: [rootPath, title],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFsInitWikiConstMeta => const TaskConstMeta(
    debugName: "init_wiki",
    argNames: ["rootPath", "title"],
  );

  @override
  AppSettings crateApiSettingsLoadSettings() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_settings,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsLoadSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsLoadSettingsConstMeta =>
      const TaskConstMeta(debugName: "load_settings", argNames: []);

  @override
  Future<List<TextChunk>> crateApiParserMarkdownToDelta({
    required String markdown,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(markdown, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_text_chunk,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiParserMarkdownToDeltaConstMeta,
        argValues: [markdown],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParserMarkdownToDeltaConstMeta =>
      const TaskConstMeta(
        debugName: "markdown_to_delta",
        argNames: ["markdown"],
      );

  @override
  Future<CrowFile> crateApiFsReadAnchor({required String rootPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rootPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_crow_file,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFsReadAnchorConstMeta,
        argValues: [rootPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFsReadAnchorConstMeta =>
      const TaskConstMeta(debugName: "read_anchor", argNames: ["rootPath"]);

  @override
  Future<String> crateApiFsReadFileAsString({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFsReadFileAsStringConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFsReadFileAsStringConstMeta =>
      const TaskConstMeta(debugName: "read_file_as_string", argNames: ["path"]);

  @override
  Future<Page> crateApiFsReadPage({
    required String rootPath,
    required String relPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rootPath, serializer);
          sse_encode_String(relPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_page,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFsReadPageConstMeta,
        argValues: [rootPath, relPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFsReadPageConstMeta => const TaskConstMeta(
    debugName: "read_page",
    argNames: ["rootPath", "relPath"],
  );

  @override
  Future<bool> crateApiSearchRebuildIndex({required String wikiRoot}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(wikiRoot, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSearchRebuildIndexConstMeta,
        argValues: [wikiRoot],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchRebuildIndexConstMeta =>
      const TaskConstMeta(debugName: "rebuild_index", argNames: ["wikiRoot"]);

  @override
  Future<void> crateApiFsRenameItem({
    required String oldPath,
    required String newPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(oldPath, serializer);
          sse_encode_String(newPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFsRenameItemConstMeta,
        argValues: [oldPath, newPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFsRenameItemConstMeta => const TaskConstMeta(
    debugName: "rename_item",
    argNames: ["oldPath", "newPath"],
  );

  @override
  bool crateApiChatSaveChatMessage({
    required String wikiRoot,
    required ChatMessage message,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(wikiRoot, serializer);
          sse_encode_box_autoadd_chat_message(message, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatSaveChatMessageConstMeta,
        argValues: [wikiRoot, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatSaveChatMessageConstMeta =>
      const TaskConstMeta(
        debugName: "save_chat_message",
        argNames: ["wikiRoot", "message"],
      );

  @override
  bool crateApiChatSaveChatSession({
    required String wikiRoot,
    required ChatSession session,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(wikiRoot, serializer);
          sse_encode_box_autoadd_chat_session(session, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatSaveChatSessionConstMeta,
        argValues: [wikiRoot, session],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatSaveChatSessionConstMeta =>
      const TaskConstMeta(
        debugName: "save_chat_session",
        argNames: ["wikiRoot", "session"],
      );

  @override
  void crateApiSettingsSaveGoogleApiKey({required String key}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsSaveGoogleApiKeyConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsSaveGoogleApiKeyConstMeta =>
      const TaskConstMeta(debugName: "save_google_api_key", argNames: ["key"]);

  @override
  void crateApiSettingsSaveTheme({required int index}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(index, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsSaveThemeConstMeta,
        argValues: [index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsSaveThemeConstMeta =>
      const TaskConstMeta(debugName: "save_theme", argNames: ["index"]);

  @override
  Future<TreeNode> crateApiFsScanDirectory({required String rootPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rootPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tree_node,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFsScanDirectoryConstMeta,
        argValues: [rootPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFsScanDirectoryConstMeta =>
      const TaskConstMeta(debugName: "scan_directory", argNames: ["rootPath"]);

  @override
  List<SearchResult> crateApiSearchSearchDocuments({
    required String query,
    required int mode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_u_8(mode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_search_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSearchSearchDocumentsConstMeta,
        argValues: [query, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchSearchDocumentsConstMeta =>
      const TaskConstMeta(
        debugName: "search_documents",
        argNames: ["query", "mode"],
      );

  @override
  Future<List<ChunkResult>> crateApiRagSearchSimilar({
    required String wikiRoot,
    required String query,
    required BigInt limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(wikiRoot, serializer);
          sse_encode_String(query, serializer);
          sse_encode_usize(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chunk_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRagSearchSimilarConstMeta,
        argValues: [wikiRoot, query, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRagSearchSimilarConstMeta => const TaskConstMeta(
    debugName: "search_similar",
    argNames: ["wikiRoot", "query", "limit"],
  );

  @override
  Future<TextAttributes> crateApiModelsTextAttributesDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_text_attributes,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsTextAttributesDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsTextAttributesDefaultConstMeta =>
      const TaskConstMeta(debugName: "text_attributes_default", argNames: []);

  @override
  Future<void> crateApiFsWriteAnchor({
    required String rootPath,
    required CrowFile crowFile,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rootPath, serializer);
          sse_encode_box_autoadd_crow_file(crowFile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFsWriteAnchorConstMeta,
        argValues: [rootPath, crowFile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFsWriteAnchorConstMeta => const TaskConstMeta(
    debugName: "write_anchor",
    argNames: ["rootPath", "crowFile"],
  );

  @override
  Future<void> crateApiFsWriteFileAsString({
    required String path,
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFsWriteFileAsStringConstMeta,
        argValues: [path, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFsWriteFileAsStringConstMeta =>
      const TaskConstMeta(
        debugName: "write_file_as_string",
        argNames: ["path", "content"],
      );

  @override
  Future<void> crateApiFsWritePage({
    required String rootPath,
    required String relPath,
    required Page page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rootPath, serializer);
          sse_encode_String(relPath, serializer);
          sse_encode_box_autoadd_page(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFsWritePageConstMeta,
        argValues: [rootPath, relPath, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFsWritePageConstMeta => const TaskConstMeta(
    debugName: "write_page",
    argNames: ["rootPath", "relPath", "page"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppSettings dco_decode_app_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AppSettings(
      themeIndex: dco_decode_i_32(arr[0]),
      recentWikis: dco_decode_list_String(arr[1]),
      googleApiKey: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ChatMessage dco_decode_box_autoadd_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_chat_message(raw);
  }

  @protected
  ChatSession dco_decode_box_autoadd_chat_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_chat_session(raw);
  }

  @protected
  CrowFile dco_decode_box_autoadd_crow_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_crow_file(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  Page dco_decode_box_autoadd_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_page(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ChatMessage dco_decode_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ChatMessage(
      id: dco_decode_String(arr[0]),
      sessionId: dco_decode_String(arr[1]),
      role: dco_decode_String(arr[2]),
      content: dco_decode_String(arr[3]),
      timestamp: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  ChatSession dco_decode_chat_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ChatSession(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      createdAt: dco_decode_i_64(arr[2]),
      updatedAt: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  ChunkResult dco_decode_chunk_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ChunkResult(
      filePath: dco_decode_String(arr[0]),
      chunkText: dco_decode_String(arr[1]),
      distance: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  CrowFile dco_decode_crow_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CrowFile(
      metadata: dco_decode_crow_metadata(arr[0]),
      settings: dco_decode_String(arr[1]),
      modules: dco_decode_String(arr[2]),
    );
  }

  @protected
  CrowMetadata dco_decode_crow_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CrowMetadata(
      title: dco_decode_String(arr[0]),
      version: dco_decode_String(arr[1]),
      createdAt: dco_decode_opt_box_autoadd_i_64(arr[2]),
      updatedAt: dco_decode_opt_box_autoadd_i_64(arr[3]),
    );
  }

  @protected
  DbHealthStatus dco_decode_db_health_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DbHealthStatus(
      status: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ChatMessage> dco_decode_list_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chat_message).toList();
  }

  @protected
  List<ChatSession> dco_decode_list_chat_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chat_session).toList();
  }

  @protected
  List<ChunkResult> dco_decode_list_chunk_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chunk_result).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SearchResult> dco_decode_list_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_search_result).toList();
  }

  @protected
  List<TextChunk> dco_decode_list_text_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_text_chunk).toList();
  }

  @protected
  List<TreeNode> dco_decode_list_tree_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tree_node).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  Page dco_decode_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Page(
      path: dco_decode_String(arr[0]),
      metadata: dco_decode_page_metadata(arr[1]),
      content: dco_decode_String(arr[2]),
    );
  }

  @protected
  PageMetadata dco_decode_page_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PageMetadata(
      title: dco_decode_String(arr[0]),
      tags: dco_decode_list_String(arr[1]),
      createdAt: dco_decode_opt_box_autoadd_i_64(arr[2]),
      updatedAt: dco_decode_opt_box_autoadd_i_64(arr[3]),
    );
  }

  @protected
  SearchResult dco_decode_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return SearchResult(
      filePath: dco_decode_String(arr[0]),
      rawStartOffset: dco_decode_usize(arr[1]),
      rawEndOffset: dco_decode_usize(arr[2]),
      exactMatchText: dco_decode_String(arr[3]),
      previewText: dco_decode_String(arr[4]),
      lineNumber: dco_decode_usize(arr[5]),
      columnNumber: dco_decode_usize(arr[6]),
      isCaseMatch: dco_decode_bool(arr[7]),
      isSyntaxClean: dco_decode_bool(arr[8]),
      isWholeWord: dco_decode_bool(arr[9]),
    );
  }

  @protected
  TextAttributes dco_decode_text_attributes(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return TextAttributes(
      bold: dco_decode_bool(arr[0]),
      italic: dco_decode_bool(arr[1]),
      strikethrough: dco_decode_bool(arr[2]),
      code: dco_decode_bool(arr[3]),
      link: dco_decode_opt_String(arr[4]),
      header: dco_decode_opt_box_autoadd_u_8(arr[5]),
    );
  }

  @protected
  TextChunk dco_decode_text_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TextChunk(
      text: dco_decode_String(arr[0]),
      attributes: dco_decode_text_attributes(arr[1]),
    );
  }

  @protected
  TreeNode dco_decode_tree_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TreeNode(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      isDirectory: dco_decode_bool(arr[2]),
      children: dco_decode_list_tree_node(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppSettings sse_decode_app_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_themeIndex = sse_decode_i_32(deserializer);
    var var_recentWikis = sse_decode_list_String(deserializer);
    var var_googleApiKey = sse_decode_opt_String(deserializer);
    return AppSettings(
      themeIndex: var_themeIndex,
      recentWikis: var_recentWikis,
      googleApiKey: var_googleApiKey,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ChatMessage sse_decode_box_autoadd_chat_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_chat_message(deserializer));
  }

  @protected
  ChatSession sse_decode_box_autoadd_chat_session(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_chat_session(deserializer));
  }

  @protected
  CrowFile sse_decode_box_autoadd_crow_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_crow_file(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  Page sse_decode_box_autoadd_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_page(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  ChatMessage sse_decode_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_sessionId = sse_decode_String(deserializer);
    var var_role = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_timestamp = sse_decode_i_64(deserializer);
    return ChatMessage(
      id: var_id,
      sessionId: var_sessionId,
      role: var_role,
      content: var_content,
      timestamp: var_timestamp,
    );
  }

  @protected
  ChatSession sse_decode_chat_session(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return ChatSession(
      id: var_id,
      title: var_title,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  ChunkResult sse_decode_chunk_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filePath = sse_decode_String(deserializer);
    var var_chunkText = sse_decode_String(deserializer);
    var var_distance = sse_decode_f_64(deserializer);
    return ChunkResult(
      filePath: var_filePath,
      chunkText: var_chunkText,
      distance: var_distance,
    );
  }

  @protected
  CrowFile sse_decode_crow_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_metadata = sse_decode_crow_metadata(deserializer);
    var var_settings = sse_decode_String(deserializer);
    var var_modules = sse_decode_String(deserializer);
    return CrowFile(
      metadata: var_metadata,
      settings: var_settings,
      modules: var_modules,
    );
  }

  @protected
  CrowMetadata sse_decode_crow_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_updatedAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    return CrowMetadata(
      title: var_title,
      version: var_version,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  DbHealthStatus sse_decode_db_health_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return DbHealthStatus(status: var_status, message: var_message);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChatMessage> sse_decode_list_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChatMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chat_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChatSession> sse_decode_list_chat_session(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChatSession>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chat_session(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChunkResult> sse_decode_list_chunk_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChunkResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chunk_result(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SearchResult> sse_decode_list_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<TextChunk> sse_decode_list_text_chunk(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TextChunk>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_text_chunk(deserializer));
    }
    return ans_;
  }

  @protected
  List<TreeNode> sse_decode_list_tree_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TreeNode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tree_node(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Page sse_decode_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_metadata = sse_decode_page_metadata(deserializer);
    var var_content = sse_decode_String(deserializer);
    return Page(path: var_path, metadata: var_metadata, content: var_content);
  }

  @protected
  PageMetadata sse_decode_page_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_createdAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_updatedAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    return PageMetadata(
      title: var_title,
      tags: var_tags,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  SearchResult sse_decode_search_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filePath = sse_decode_String(deserializer);
    var var_rawStartOffset = sse_decode_usize(deserializer);
    var var_rawEndOffset = sse_decode_usize(deserializer);
    var var_exactMatchText = sse_decode_String(deserializer);
    var var_previewText = sse_decode_String(deserializer);
    var var_lineNumber = sse_decode_usize(deserializer);
    var var_columnNumber = sse_decode_usize(deserializer);
    var var_isCaseMatch = sse_decode_bool(deserializer);
    var var_isSyntaxClean = sse_decode_bool(deserializer);
    var var_isWholeWord = sse_decode_bool(deserializer);
    return SearchResult(
      filePath: var_filePath,
      rawStartOffset: var_rawStartOffset,
      rawEndOffset: var_rawEndOffset,
      exactMatchText: var_exactMatchText,
      previewText: var_previewText,
      lineNumber: var_lineNumber,
      columnNumber: var_columnNumber,
      isCaseMatch: var_isCaseMatch,
      isSyntaxClean: var_isSyntaxClean,
      isWholeWord: var_isWholeWord,
    );
  }

  @protected
  TextAttributes sse_decode_text_attributes(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bold = sse_decode_bool(deserializer);
    var var_italic = sse_decode_bool(deserializer);
    var var_strikethrough = sse_decode_bool(deserializer);
    var var_code = sse_decode_bool(deserializer);
    var var_link = sse_decode_opt_String(deserializer);
    var var_header = sse_decode_opt_box_autoadd_u_8(deserializer);
    return TextAttributes(
      bold: var_bold,
      italic: var_italic,
      strikethrough: var_strikethrough,
      code: var_code,
      link: var_link,
      header: var_header,
    );
  }

  @protected
  TextChunk sse_decode_text_chunk(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_attributes = sse_decode_text_attributes(deserializer);
    return TextChunk(text: var_text, attributes: var_attributes);
  }

  @protected
  TreeNode sse_decode_tree_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_isDirectory = sse_decode_bool(deserializer);
    var var_children = sse_decode_list_tree_node(deserializer);
    return TreeNode(
      name: var_name,
      path: var_path,
      isDirectory: var_isDirectory,
      children: var_children,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_settings(AppSettings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.themeIndex, serializer);
    sse_encode_list_String(self.recentWikis, serializer);
    sse_encode_opt_String(self.googleApiKey, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_chat_message(
    ChatMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_chat_message(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_chat_session(
    ChatSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_chat_session(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_crow_file(
    CrowFile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_crow_file(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_page(Page self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_page(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_chat_message(ChatMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.role, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_i_64(self.timestamp, serializer);
  }

  @protected
  void sse_encode_chat_session(ChatSession self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_chunk_result(ChunkResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.filePath, serializer);
    sse_encode_String(self.chunkText, serializer);
    sse_encode_f_64(self.distance, serializer);
  }

  @protected
  void sse_encode_crow_file(CrowFile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_crow_metadata(self.metadata, serializer);
    sse_encode_String(self.settings, serializer);
    sse_encode_String(self.modules, serializer);
  }

  @protected
  void sse_encode_crow_metadata(CrowMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_opt_box_autoadd_i_64(self.createdAt, serializer);
    sse_encode_opt_box_autoadd_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_db_health_status(
    DbHealthStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.status, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chat_message(
    List<ChatMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chat_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chat_session(
    List<ChatSession> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chat_session(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chunk_result(
    List<ChunkResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chunk_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_search_result(
    List<SearchResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_text_chunk(
    List<TextChunk> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_text_chunk(item, serializer);
    }
  }

  @protected
  void sse_encode_list_tree_node(
    List<TreeNode> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tree_node(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_page(Page self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_page_metadata(self.metadata, serializer);
    sse_encode_String(self.content, serializer);
  }

  @protected
  void sse_encode_page_metadata(PageMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_opt_box_autoadd_i_64(self.createdAt, serializer);
    sse_encode_opt_box_autoadd_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_search_result(SearchResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.filePath, serializer);
    sse_encode_usize(self.rawStartOffset, serializer);
    sse_encode_usize(self.rawEndOffset, serializer);
    sse_encode_String(self.exactMatchText, serializer);
    sse_encode_String(self.previewText, serializer);
    sse_encode_usize(self.lineNumber, serializer);
    sse_encode_usize(self.columnNumber, serializer);
    sse_encode_bool(self.isCaseMatch, serializer);
    sse_encode_bool(self.isSyntaxClean, serializer);
    sse_encode_bool(self.isWholeWord, serializer);
  }

  @protected
  void sse_encode_text_attributes(
    TextAttributes self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.bold, serializer);
    sse_encode_bool(self.italic, serializer);
    sse_encode_bool(self.strikethrough, serializer);
    sse_encode_bool(self.code, serializer);
    sse_encode_opt_String(self.link, serializer);
    sse_encode_opt_box_autoadd_u_8(self.header, serializer);
  }

  @protected
  void sse_encode_text_chunk(TextChunk self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_text_attributes(self.attributes, serializer);
  }

  @protected
  void sse_encode_tree_node(TreeNode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.isDirectory, serializer);
    sse_encode_list_tree_node(self.children, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
