// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `open_db`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Initialise la base de données de chat
bool initChatDb({required String wikiRoot}) =>
    RustLib.instance.api.crateApiChatInitChatDb(wikiRoot: wikiRoot);

/// Sauvegarde une nouvelle session
bool saveChatSession({
  required String wikiRoot,
  required ChatSession session,
}) => RustLib.instance.api.crateApiChatSaveChatSession(
  wikiRoot: wikiRoot,
  session: session,
);

/// Liste toutes les sessions
List<ChatSession> getChatSessions({required String wikiRoot}) =>
    RustLib.instance.api.crateApiChatGetChatSessions(wikiRoot: wikiRoot);

/// Supprime une session et tous ses messages associés
bool deleteChatSession({required String wikiRoot, required String sessionId}) =>
    RustLib.instance.api.crateApiChatDeleteChatSession(
      wikiRoot: wikiRoot,
      sessionId: sessionId,
    );

/// Renomme une session
bool renameChatSession({
  required String wikiRoot,
  required String sessionId,
  required String newTitle,
}) => RustLib.instance.api.crateApiChatRenameChatSession(
  wikiRoot: wikiRoot,
  sessionId: sessionId,
  newTitle: newTitle,
);

/// Sauvegarde un message
bool saveChatMessage({
  required String wikiRoot,
  required ChatMessage message,
}) => RustLib.instance.api.crateApiChatSaveChatMessage(
  wikiRoot: wikiRoot,
  message: message,
);

/// Récupère les messages d'une session
List<ChatMessage> getChatMessages({
  required String wikiRoot,
  required String sessionId,
}) => RustLib.instance.api.crateApiChatGetChatMessages(
  wikiRoot: wikiRoot,
  sessionId: sessionId,
);

class ChatMessage {
  final String id;
  final String sessionId;
  final String role;
  final String content;
  final PlatformInt64 timestamp;
  final List<String>? sources;

  const ChatMessage({
    required this.id,
    required this.sessionId,
    required this.role,
    required this.content,
    required this.timestamp,
    this.sources,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sessionId.hashCode ^
      role.hashCode ^
      content.hashCode ^
      timestamp.hashCode ^
      sources.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sessionId == other.sessionId &&
          role == other.role &&
          content == other.content &&
          timestamp == other.timestamp &&
          sources == other.sources;
}

class ChatSession {
  final String id;
  final String title;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const ChatSession({
    required this.id,
    required this.title,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ createdAt.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
