// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `deobfuscate`, `obfuscate`, `scan_dir_recursive`

Future<void> initWiki({required String rootPath, required String title}) =>
    RustLib.instance.api.crateApiFsInitWiki(rootPath: rootPath, title: title);

Future<void> writeAnchor({
  required String rootPath,
  required CrowFile crowFile,
}) => RustLib.instance.api.crateApiFsWriteAnchor(
  rootPath: rootPath,
  crowFile: crowFile,
);

Future<CrowFile> readAnchor({required String rootPath}) =>
    RustLib.instance.api.crateApiFsReadAnchor(rootPath: rootPath);

Future<TreeNode> scanDirectory({required String rootPath}) =>
    RustLib.instance.api.crateApiFsScanDirectory(rootPath: rootPath);

Future<Page> readPage({required String rootPath, required String relPath}) =>
    RustLib.instance.api.crateApiFsReadPage(
      rootPath: rootPath,
      relPath: relPath,
    );

Future<void> writePage({
  required String rootPath,
  required String relPath,
  required Page page,
}) => RustLib.instance.api.crateApiFsWritePage(
  rootPath: rootPath,
  relPath: relPath,
  page: page,
);

Future<void> createFile({required String path}) =>
    RustLib.instance.api.crateApiFsCreateFile(path: path);

Future<void> createDirectory({required String path}) =>
    RustLib.instance.api.crateApiFsCreateDirectory(path: path);

Future<void> deleteItem({required String path}) =>
    RustLib.instance.api.crateApiFsDeleteItem(path: path);

Future<void> renameItem({required String oldPath, required String newPath}) =>
    RustLib.instance.api.crateApiFsRenameItem(
      oldPath: oldPath,
      newPath: newPath,
    );

Future<String> readFileAsString({required String path}) =>
    RustLib.instance.api.crateApiFsReadFileAsString(path: path);

Future<void> writeFileAsString({
  required String path,
  required String content,
}) => RustLib.instance.api.crateApiFsWriteFileAsString(
  path: path,
  content: content,
);
