// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `f32_vec_to_bytes`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Vide la base vectorielle
Future<bool> clearIndex({required String wikiRoot}) =>
    RustLib.instance.api.crateApiRagClearIndex(wikiRoot: wikiRoot);

/// Initialise le modèle d'embedding en mémoire
Future<bool> initEmbedder() => RustLib.instance.api.crateApiRagInitEmbedder();

/// Indexe le contenu d'un fichier dans la base vectorielle
Future<bool> indexFile({
  required String wikiRoot,
  required String filePath,
  required String content,
}) => RustLib.instance.api.crateApiRagIndexFile(
  wikiRoot: wikiRoot,
  filePath: filePath,
  content: content,
);

/// Cherche les documents similaires dans le wiki
Future<List<ChunkResult>> searchSimilar({
  required String wikiRoot,
  required String query,
  required BigInt limit,
}) => RustLib.instance.api.crateApiRagSearchSimilar(
  wikiRoot: wikiRoot,
  query: query,
  limit: limit,
);

class ChunkResult {
  final String filePath;
  final String chunkText;
  final double distance;

  const ChunkResult({
    required this.filePath,
    required this.chunkText,
    required this.distance,
  });

  @override
  int get hashCode =>
      filePath.hashCode ^ chunkText.hashCode ^ distance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChunkResult &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath &&
          chunkText == other.chunkText &&
          distance == other.distance;
}
